import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <ul>
              <li>
                <a className="link" href="/push">
                  push
                </a>
              </li>
              <li>
                <a className="link" href="/pull">
                  pull
                </a>
              </li>
              <li>
                <a className="link" href="/legs">
                  legs
                </a>
              </li>
              <li>
                <a className="link" href="/cardio">
                  cardio
                </a>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
